### ISSUE TITLE
大数相加参考资料

### ISSUE THREAD

**Issue by xrksudy** [FE-star/exercise2#25]
大数相加平时也没多考虑，一时不知道如何下手，搜索到一篇比较好的文章：
http://www.plqblog.com/views/article.php?id=29

javascript一系列的上限下限(文章中的图，挺不错的)
![1468042984788341](https://user-images.githubusercontent.com/962712/29358182-b0ed7164-82ac-11e7-9629-10c0a36ce55f.png)

或者可以参考第三方比较成熟的类库[bignumber.js](https://github.com/MikeMcl/bignumber.js/),学习下实现思路及边界处理等。

**Comment by Fridolph** [comment]
惭愧惭愧  。。 刚提了pr ， 就是借（抄）鉴的这个
